#!/bin/bash
#PBS -l nodes=1:ppn=1,walltime=32:00:00,vmem=20gb
#PBS -N app-contract-optic-radiation

# create csf mask
if [ ! -f csf.nii.gz ]; then
	time singularity exec -e docker://brainlife/mrtrix3:3.0_RC3 ./csf.sh
fi

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

# create hemisphere ribbons, ribbon, and visual area niftis in diffusion space
if [ ! -f ribbon.nii.gz ]; then
	time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:6.0.0 ./convert.sh
fi

# mask visual area by hemisphere
if [ ! -f ribbon_right.nii.gz ]; then
	time singularity exec -e docker://brainlife/fsl:latest ./mask.sh
fi

# generate pdf file
if [ ! -f ./tmpSubj/dtiinit/dti/bin/pdf.nii.gz ]; then
	time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./contrackPrep/opticRadiationContrackPrep
fi

# reslice everything in dtiinit/bin to anat space
if [ ! -f ./tmpSubj/dtiinit/dti/bin/pdf_dtiinit.nii.gz ]; then
	time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:6.0.0 ./convert_dtiinit.sh
fi

# generate pdf file
if [ ! -f ./tmpSubj/dtiinit/dti/bin/pdf.nii.gz ]; then
	time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./contrackTrack/opticRadiationContrackTracking
fi

# cleanup
mkdir -p track

if [ -f track.tck ]; then
	mkdir ./wmc ./wmc/tracts
	mv ./track.tck ./track/
	mv ./output.mat ./wmc/classification.mat
	mv ./tracts/* ./wmc/tracts/
	mv ./output_fibercounts.txt ./wmc/
	#rm -rf tmpSubj *.nii.gz* *.mif* ./bin ./logs ./tracts license.txt
	exit 0;
else
	echo "tracking failed"
	exit 1;
fi
