#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=1:00:00
#PBS -N app-contract-optic-radiation

# create csf mask
if [ ! -f csf.nii.gz ]; then
	time singularity exec -e docker://brainlife/mrtrix3:3.0_RC3 ./csf.sh
fi

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

# create hemisphere ribbons, ribbon, and visual area niftis in diffusion space
if [ ! -f ribbon.nii.gz ]; then
	time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:6.0.0 ./convert.sh
fi

# mask visual area by hemisphere
if [ ! -f varea.nii.gz ]; then
	time singularity exec -e docker://brainlife/fsl:latest ./mask.sh
fi

# perform contrack tracking
if [ ! -f track.tck ]; then
	time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/opticRadiationContrack
fi

# cleanup
mkdir -p track

if [ -f track.tck ]; then
	mv ./track.tck ./track/
	mkdir ./wmc ./wmc/tracts/
	mv ./output.mat ./wmc/classification.mat
	mv ./tracts/* ./wmc/tracts/
	mv ./output_fibercounts.txt ./wmc/
	rm -rf ./tmpSubj ./*.nii.gz* ./*.mif* ./tracts
	exit 0;
else
	echo "tracking failed"
	exit 1;
fi
