#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=6:00:00
#PBS -N app-contract-optic-radiation

if [ ! -f csf.nii.gz ]; then
	time singularity exec -e docker://brainlife/mrtrix3:3.0_RC3 ./csf.sh
fi

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:6.0.0 ./convert.sh

time singularity exec -e docker://brainlife/fsl:latest ./mask.sh

time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/opticRadiationContrack

# cleanup
mkdir -p track

if [ -f track.tck ]; then
	mv track.tck ./track/
	mv output.mat ./wmc/classification.mat
	mv tracts ./wmc/
	mv output_fibercounts.txt ./wmc/
	rm tmpSubj *.nii.gz* *.mif*
	exit 0;
else
	echo "tracking failed"
	exit 1;
fi
